"""Add assignee_id to tasks table

Revision ID: 6e78ab76ddd5
Revises: 6e621a9599b9
Create Date: 2025-05-04 19:43:56.288069

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6e78ab76ddd5'
down_revision: Union[str, None] = '6e621a9599b9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tasks', sa.Column('assignee_id', sa.UUID(), nullable=True))
    op.alter_column('tasks', 'team_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.create_foreign_key(None, 'tasks', 'users', ['assignee_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'tasks', type_='foreignkey')
    op.alter_column('tasks', 'team_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.drop_column('tasks', 'assignee_id')
    # ### end Alembic commands ###
